MP-28 JSON export
CRSU-Apps/MetaPairwise pull request #18
Opened 2024-08-09 11:40 UTC by JanionNevill

This is to support integration with TERA tools.

2024-08-30 07:58 UTC, JanionNevill commented
@WillRobinn Will you get a chance to look at this soon? Bond are chasing for this.

2024-09-02 09:53 UTC, nabury requested changes

2024-09-02 09:53 UTC, nabury commented on tests/testthat/test-export.R
I'm getting this error when I run the tests 
<img width="659" alt="Screenshot 2024-09-02 at 10 29 10" src="https://github.com/user-attachments/assets/369ed2cc-453d-437f-9a75-4b69a2b7ae87">

2024-09-02 09:53 UTC, nabury commented on R/export.R
Add some comments to this file to explain the logic behind the conditionals

2024-09-02 09:53 UTC, nabury commented on R/export.R
Can any of this file be generalised as a lot of the lines are repeated? My concern is that it would be easy for there to be a typo that was missed. Or could the tests be expanded to include all combinations if that is less work?

2024-09-02 10:41 UTC, JanionNevill commented on tests/testthat/test-export.R
Fixed, and changed to temporary directories

2024-09-02 11:37 UTC, JanionNevill commented on R/export.R
Added

2024-09-02 11:37 UTC, JanionNevill commented on R/export.R
I've done the best I can for minimal effort, but there's still some duplication

2024-09-02 12:46 UTC, nabury approved these changes
Looks good - downloads working correctly, tests run. I pushed a correction for a typo.

2024-09-02 13:58 UTC, merged